### ISSUE TITLE
Missing file data/0/test.txt

### ISSUE THREAD

**Issue by ccyun1127** [lancopku/Skeleton-Based-Generation-Model#10]
Hi, I am trying on your code.
However, there is no 'data/0/test.txt'.
Could you please share the data or the format you use?
Thank you!

**Comment by Jingjing-NLP** [comment]
hi, this dir is generated automatically. please see  the following code in [run_summarization.py](https://github.com/lancopku/Skeleton-Based-Generation-Model/blob/master/run_summarization.py)
<img width="735" alt="image" src="https://user-images.githubusercontent.com/85208576/171077163-9049394b-fda1-4964-b098-07b38a74de66.png">
