### ISSUE TITLE
running ./run_test.sh -> FileNotFoundError: [Errno 2] No such file or directory: 'data/0/test.txt'

### ISSUE THREAD

**Issue by johndpope** [lancopku/Skeleton-Based-Generation-Model#3]
do I have to wait for training to finish before running test?
can't it run on half baked training?

(tf14) ➜  Skeleton-Based-Generation-Model git:(master) ✗ ./run_test.sh
Traceback (most recent call last):
  File "calculate_relevance_BLEU.py", line 119, in <module>
    gold_input, gold_output = read_gold_true("data/0/test.txt")
  File "calculate_relevance_BLEU.py", line 20, in read_gold_true
    reader = codecs.open(read_file, 'r', 'utf-8')
  File "/Users/jpope/miniconda2/envs/tf14/lib/python3.6/codecs.py", line 897, in open
    file = builtins.open(filename, mode, buffering)
FileNotFoundError: [Errno 2] No such file or directory: 'data/0/test.txt'
(tf14) ➜  Skeleton-Based-Generation-Model git:(master) ✗ ./run_train.sh

**Comment by jingjingxupku** [comment]
Not all training process, just the training of skeleton extraction module. Thank you for your question!

**Comment by johndpope** [comment]
No such file or directory: 'data/0/test.txt'

Seems like a file is missing

**Comment by johndpope** [comment]
Or a step after training?

**Comment by jingjingxupku** [comment]
data/0/test.txt is generated by the skeleton extraction module.  The testing script only works after the finish of training skeleton extraction module (plus one saving step of the generator module).

**Comment by johndpope** [comment]
works - thanks
<img width="615" alt="screen shot 2018-08-23 at 2 06 38 pm" src="https://user-images.githubusercontent.com/289994/44543526-c5b8b580-a6dd-11e8-8108-2e6ce1563885.png">
