### ISSUE TITLE
not an issue  - generated results / sentence discriminator / sanity checker

### ISSUE THREAD

**Issue by johndpope** [lancopku/Skeleton-Based-Generation-Model#5]
after running train + test
I see the following sentences spat out (1MB)
https://gist.github.com/johndpope/be214c798975b4057e70a4f7849bd3fb

Looking through data - I can see some generated / valid sentences. But not all. 
{"example": " the beer delivery was . ", "label": "1"}

I'm convinced a flaw around all the text generation is being able to definitely judge if a sentence is grammatically and syntactically correct.  Does such an library exist to do this which could be incorporated into pipeline? Need a way to disregard erroneous data.

digging online 
https://stackoverflow.com/questions/10252448/how-to-check-whether-a-sentence-is-correct-simple-grammar-check-in-python

found this -> 
https://pypi.org/project/language-check/
 pip install --upgrade language-check

>>> import language_check
>>> tool = language_check.LanguageTool('en-US')
>>> text = u' the beer delivery was .'
>>> matches = tool.check(text)

it does find these problems
[Match({'fromy': 0, 'fromx': 0, 'toy': 0, 'tox': 3, 'ruleId': 'UPPERCASE_SENTENCE_START', 'msg': 'This sentence does not start with an uppercase letter', 'replacements': ['The'], 'context': 'the beer delivery was .', 'contextoffset': 0, 'offset': 0, 'errorlength': 3, 'category': 'Capitalization', 'locqualityissuetype': 'typographical'}), Match({'fromy': 0, 'fromx': 21, 'toy': 0, 'tox': 23, 'ruleId': 'COMMA_PARENTHESIS_WHITESPACE', 'msg': "Don't put a space before the full stop", 'replacements': ['.'], 'context': 'the beer delivery was .', 'contextoffset': 21, 'offset': 21, 'errorlength': 2, 'category': 'Miscellaneous', 'locqualityissuetype': 'whitespace'})]

but after removing the . at the end - and making start of sentence upper case - it can't find any other problems with it.  I think microsoft word can though? 

if the generator was  able to filter for sentences that failed - this would enhance results a leap, no?

Seems like the NLP space / community needs a sentence sanity checker before we can get any real generator with high score.

**Comment by jingjingxupku** [comment]
They are not our generated stories. This file stores the skeletons of sentences. The skeleton is used to capture key meanings of sentences, and the correct grammar is not necessary. Thanks for your suggestion.
